
const datas = [
    {
        id:"Cars",
        img:'color',
        title:"Cars",
    },
    {
        id:"Home",
        img:'color',
        title:"Home",
    },
    {
        id:"Electronics",
        img:'color',
        title:"Electronics",
    },
    {
        id:"Jobs",
        img:'color',
        title:"Jobs",
    },
    {
        id:"FashionStyle",
        img:'color',
        title:"FashionStyle",
    },
    {
        id:"ChildrensWorld",
        img:'color',
        title:"ChildrensWorld",
    },
    {
        id:"business-service",
        img:'color',
        title:"business-service",
    },
    {
        id:"Agriculture",
        img:'color',
        title:"Agriculture",
    },
]
export default datas;