export  const ActionType = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SELECTED_CATEGORE_PRODUCT: "SELECTED_CATEGORE_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SEARCH_VALUE:"SEARCH_VALUE",
  SET_IMAG:"SET_IMAG",
};

